# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build and complie the application"
  lane :compile_app do |options|
    should_clean = options.fetch(:clean, false)
    if should_clean
      command_task = "clean"
    else
      command_task = ""
    end
    command_task += " assembleDebug"
    gradle(task: command_task.strip)
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    build_release_apk
    appcenter_upload(api_token: "#{ENV['APP_CENTER_API_TOKEN']}", 
    owner_name: "#{ENV['APP_CENTER_ACCOUNT_NAME']}",
    app_name: "Inner-Circle",
    notify_testers: true
    )
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    upload_to_play_store
  end

  lane :build_release_apk do
    gradle(task: "clean assembleRelease")
  end
end
